version: '3.8'

services:
  ups-monitor:
    image: tinchodeluca/ups-monitor:latest
    container_name: ups-monitor
    privileged: true
    user: root
    restart: unless-stopped

    environment:
      - UPS_VID=0x0665
      - UPS_PID=0x5161
      - CHECK_INTERVAL=10
      - SHUTDOWN_VOLTAGE=11.0
      - SHUTDOWN_DELAY=300

    volumes:
      - ./data:/app/data
      - /dev/bus/usb:/dev/bus/usb
